### PR TITLE
Contact page

### LINKED ISSUE #72: Create a About page and individual user page
Create a about page for the site and individual user page

### PR DESCRIPTION
**Pull request by uchadh**

### CODE REVIEW

**Review by jungeebah — APPROVED** [review]
Looks nice in all screen

**Comment by uchadh** [comment]
> Looks nice in all screen

Thank you. Spent lot of hours for all those sizes.

**Comment by jungeebah** [comment]
Need to change the space between name and photo in large screen size scss

**Comment by jungeebah** [comment]
use theme colors----backlog this

**Pull request merged**
