### PR TITLE
fixed the hommage and rashmono

### PR DESCRIPTION
**Pull request by jungeebah**
fixed homage and rashmono

### CODE REVIEW

**Comment by uchadh** [comment]
Can we put “Not Rated”
Instead of blank?

**Comment by jungeebah** [comment]
We can try with NR. As the rating key value is displayed in our Display and long sentence cannot be fitted

**Comment by uchadh** [comment]
Ok. Let’s put NR

**Comment by jungeebah** [comment]
Since there are some issues with display and will need to add the review for roshmono so closing it till i fix that

**Pull request closed without merging**
